# 

In [3]:
import numpy as np

In [4]:
n = 4
k = 2

In [12]:
A, _, _ = np.linalg.svd(np.random.uniform(size=(n, k)))
A = A[:, :k]
A[:,0] @ A[:,1]

-5.551115123125783e-17

In [27]:
A = np.zeros((n,k))
A[0,0]=1
A[1,1]=1

In [29]:
def T_A(A):
    k = A.shape[1]
    A_p,_,_ = np.linalg.svd(A)
    A_p = A_p[:, k:]
    B = []
    for i in range((n-k)*k):
        b_i = np.zeros((n-k,k))
        b_i[i//k, i%k] = 1
        B.append(b_i)


    C = []
    for i in range(k):
        for j in range(k):
            if i < j:
                c = np.zeros((k,k))
                c[i,j] = 1
                c[j,i] = -1
                C.append(c)      

    TB = []
    for b in B:
        TB.append(np.matmul(A,np.zeros((k,k)))+np.matmul(A_p, b))
    for c in C:
        TB.append(np.matmul(A,c)+np.matmul(A_p, np.zeros((n-k,k))))
    return C,B,TB, A_p

In [30]:
C,B,TB, A_p = T_A(A)

In [31]:
for b in TB:
    print(((np.matmul(b.T,A)+np.matmul(A.T,b))>1e-8).astype('float'))

[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]


In [32]:
C

[array([[ 0.,  1.],
        [-1.,  0.]])]

In [33]:
for b in TB:
    print(b)

[[0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]]
[[ 0.  1.]
 [-1.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [34]:
print(len(TB))
print(int(k*(k-1)/2+(n-k)*k))

5
5


In [22]:
A, A_p

(array([[-0.14304736,  0.10261944],
        [-0.22737197, -0.17018496],
        [-0.86107241, -0.41683796],
        [-0.43173342,  0.88699067]]),
 array([[-0.72411366, -0.6668329 ],
        [-0.63818129,  0.71558627],
        [ 0.2494282 , -0.15028639],
        [ 0.07854696,  0.14381996]]))